config/routes.rb
Pollster::Application.routes.draw do
  get "questions/index"

  get "questions/new"

  get "questions/show"

  get "questions/edit"

  get "questions/update"

  get "questions/destroy"

  root :to => "polls#index"
   
  resources :polls
  resources :questions
  

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name, :edit_path, :survey_path
  
  before_create :generate_edit_path
  before_create :generate_survey_path
  
private

  def generate_edit_path
    rand_num = '%010d' % rand(10 ** 10).to_s
    if Poll.find_by_edit_path(rand_num)
      self.create
    else
      self.edit_path = rand_num
    end
  end
  
  def generate_survey_path
    temp_survey_path =  self.name[0..5].downcase.gsub(' ','')
    if Poll.find_by_survey_path(temp_survey_path)
      self.survey_path = temp_survey_path + rand(99).to_s
    else
      self.survey_path = temp_survey_path
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body, :poll_id
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :body, :question_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end
  
  def new
    @poll = Poll.new
  end
  
  def create
    @poll = Poll.new(params[:poll])
    @poll.save
    redirect_to(polls_path)
    
  end
   
  def show
    @poll = Poll.find_by_survey_path(params[:id])
  end
  
  def edit
    @poll = Poll.find_by_edit_path(params[:id])
  end
  
  def update
    @poll = Poll.find(params[:id])
    @poll.update_attributes(params[:poll])
    redirect_to(polls_path)
  end
  
  def destroy
    @poll = Poll.find(params[:id])
    @poll.delete
    redirect_to(polls_path)
  end
  
  

  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(params[:question])
    
    @question.save
    redirect_to(polls_path)
    
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">

	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>

	      <!-- Be sure to leave the brand out there if you want it shown -->
	      <a class="brand" href="../">Ask People Crap</a>

	      <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse">
	        <ul class="nav">
					<li><%= link_to "Polls", polls_path %>
					<li><%= link_to "Create a Poll", new_poll_path %>
	      </div>

	    </div>
	  </div>
	</div>
	
	
<div class="container-fluid">
	<div class="row">
		<div class="span8"><%= yield %></div>
		<div class="span3">
			<h2>About Us</h2>
			We are here so you can ask people crap. Seems pretty simple. 
		</div>
	</div>

</div>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>


<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :poll_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>

	<div class="form-actions">
			<%= link_to 'Add a question', new_question_path, :class => 'btn btn-primary' %>
	</div>


<% end %>

app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:edit_path) %></th>
      <th><%= model_class.human_attribute_name(:survey_path) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.id %></td>
        <td><%= poll.name %></td>
        <td><%= link_to poll.edit_path, "polls/#{poll.edit_path}/edit" %></td>
        <td><%= link_to poll.survey_path, "polls/#{poll.survey_path}" %></td>
        <td><%=l poll.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      "polls/#{poll.edit_path}/edit", :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_path(poll),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Poll", new_poll_path, :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>


<%= render 'form'%>

app/views/polls/show.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poll.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
</div>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1>Ask a question yo </h1>

<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>


<% end %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>